/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#a5d0b8',
        'surface-container-low': '#eef6ee',
        'header-fill': '#e8eef7',
        'tertiary-fixed': '#dbe5e0',
        'surface-container-highest': '#dde5dd',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#3f4945',
        'on-tertiary-container': '#868f8b',
        'on-error': '#ffffff',
        'tertiary-container': '#1f2825',
        'secondary-container': '#aeeecb',
        'outline-variant': '#c1c8c2',
        'on-secondary-fixed': '#002114',
        secondary: '#2c694e',
        primary: '#00160c',
        'surface-container-high': '#e2eae3',
        'on-primary-container': '#6d9681',
        'tertiary-fixed-dim': '#bfc9c4',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#95d4b3',
        'surface-dim': '#d4dcd5',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#ebf3eb',
        'surface-blue': '#f6f9ff',
        'on-primary-fixed': '#002114',
        tertiary: '#0a1310',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#a5d0b8',
        'surface-variant': '#dde5dd',
        'on-primary-fixed-variant': '#264e3c',
        'on-surface-subtle': '#414844',
        'on-tertiary-fixed': '#141d1b',
        'surface-tint': '#3e6653',
        'on-secondary-fixed-variant': '#0e5138',
        'on-surface-variant': '#414844',
        outline: '#717973',
        'surface-container': '#e8f0e8',
        background: '#f4fbf4',
        'on-secondary-container': '#316e52',
        'border-muted': '#c1c8c2',
        'surface-bright': '#f4fbf4',
        surface: '#f4fbf4',
        'inverse-surface': '#2b322d',
        'primary-fixed': '#c0edd4',
        'on-surface': '#161d19',
        'primary-container': '#012d1d',
        'secondary-fixed': '#b1f0ce',
        'on-background': '#161d19',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-xs': '4px',
        'container-padding': '16px',
        'stack-md': '16px',
        'column-gap': '20px',
        'stack-lg': '24px',
        'drawer-width': '288px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-bold': ['Inter'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
